### ISSUE TITLE
index.html has a typo in 'esgit' URL 

### ISSUE THREAD

**Issue by elingerojo** [wmhilton/nde#1]
In `index.html` there is a typo where `dist/` appears twice.

**Comment by billiegoose** [comment]
Actually the URL is correct! The first "dist" is the branch name, and the second "dist" is the folder name.
But I was told yesterday the website is not loading correctly, so there is probably a typo *somewhere* I need to fix.

**Comment by billiegoose** [comment]
I deleted that branch around the same time I published `isomorphic-git` on npm. I have updated the links!

**Comment by elingerojo** [comment]
Got it!

The double `dist/dist/` link https://cdn.rawgit.com/wmhilton/esgit/dist/dist/for-future.js **responds 404**

...but the single `dist/` link https://cdn.rawgit.com/wmhilton/esgit/dist/for-future.js **responds OK**. So that, I thought it was a typo.

Understand that you changed further to the `isomorphic-git`

I am glad is loading now.

**Comment by billiegoose** [comment]
Ah.. I see. I originally had a dist folder in the dist branch, but then I got rid of it in 758ff1c7ee696980a6cbd36eb698ad1effd5f947 so that I could switch between the two branches without conflicts. I was committing the dist version frequently while testing it to make sure it worked before publishing it to npm/unpkg. But I didn't want the dist versions committed in the master branch because then every copy would get downloaded during a git clone, and I use esgit to clone esgit for some of the unit tests and.....

... so thank goodness it works now anyway.
